name: dave
dependencies:
- flask=0.10.1=py35_1
- jinja2=2.8=py35_0
- numpy=1.11.0=py35_0
- llvmlite=0.20.0
- numba=0.35.0
- pip=8.1.1=py35_1
- python=3.5.1=0
- werkzeug=0.11.9=py35_0
- pytest=3.0.5
- gevent=1.2.1
- pip:
  - astropy==1.2.1
  - requests==2.10.0
  - flask-session==0.3.0
  - hypothesis==3.4.2
  - python-magic==0.4.12
  - pylru==1.0.4
  - h5py==2.7.1
  - netCDF4==1.3.0
